---
title: Honors and Awards
---

# 2024

- *Graduate Student Instructor Award*: Recognizes a graduate student instructor (GSIs) who has made an outstanding contribution to teaching and mentoring students in the Biostatistics department. Nomination.

- *Citizenship and Outreach Award*: Recognizes a student who has made major contributions to the life and culture of the department, and/or major contributions to outreach with the School, University, or larger community. Nomination.

- *Student Leader of the Year Award*: Honors a student who has shown exemplary diligence in leading a Public Health Student Organization and whose work, dedication, and passionate leadership has profoundly impacted the SPH community. Nomination.

# 2023

- *Citizenship and Outreach Award*: Recognizes a student who has made major contributions to the life and culture of the department, and/or major contributions to outreach with the School, University, or larger community. Honorable Mention.

- *Unsung Hero Award*: Honors an individual who has demonstrated a commitment to their student organization and student life at UM-SPH and whose contributions have significantly enhanced the UM-SPH community. Honorable Mention.

# 2021

- *Norris Peterson Award*: Honors one PLU senior economics student demonstrating high scholastic achievement.

# 2019

- *Stanley and Terryl Brue Economics Excellence Scholar*: Recognizes one economics student demonstrating exemplary coursework.

- *Heike A Phelps Memorial Scholar*: Awarded for an internship exploring future career, academic, and personal goals and opportunities.
